# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('meta_opis', models.TextField()),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Человека'},
        ),
    ]
