# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblab', '0002_auto_20171211_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
